name: CI

on:
  push:
  pull_request:

jobs:
  static-analysis:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install -e .

  wheel-build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    needs: static-analysis
    runs-on: ${{ matrix.os }}
    env:
      PYTHON: ${{ matrix.python-version }}
      CIBW_BUILD: "cp3*-manylinux_x86_64"
      CIBW_SKIP: "cp310-manylinux_x86_64"
      CIBW_BUILD_VERBOSITY: "1"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Upload wheel data
        run: python -m twine upload dist/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
